### ISSUE TITLE
make tests runnable by community

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client-ts#102]
currently they require a github token from someone in the atomisthq organization, and with access to private repos.

**Comment by jessitron** [comment]
I have a branch for this, nortissej/testing-for-mortals.

Moved some tests to a different directory, made public/private configurable, they run locally

but I get a failure on Travis, which manifests as a timeout, which means that _one_ of the UnhandledPromiseExceptions in the log is causing something to fail and then die without calling done().
Trying to narrow that down in the branch, which is why it's a mess.

**Comment by ddgenome** [comment]
Can this be closed now? #100
