### ISSUE TITLE
Add registration policy support

### ISSUE THREAD

**Issue by tanya-coding** [atomist/automation-client-ts#104]
**Ephemeral policy**
Use "ephemeral" policy for ad-hoc clients (dev playground etc). These registrations will not survive restarts, all intents will be removed from bot and events will not be buffered:

```
{
  "name": "SomeRegistration",
  "policy": {"name": "ephemeral"},
  ...
}
```

**Durable policy**
For clients that perform rolling upgrades and need to survive restarts and have their events buffered, use "durable" policy:

```
{
  "name": "SomeRegistration",
  "policy": {"name": "durable"},
  ...
}
```

**Comment by cdupuis** [comment]
fixed in 6018059044ca4ad27a016a1a173af4c6c9df4514
