### ISSUE TITLE
Provide gql:gen script that doesn't fail if `graphql` does not exist

### ISSUE THREAD

**Issue by cdupuis** [atomist/automation-client-ts#130]
Right now the gql:gen script fails when there are no graphql files matching the pattern. We should fix that. 

That command should be wrapped with a CLI command, like `atomist generate typings` or so.

**Comment by ddgenome** [comment]
This will also require updating client projects.

**Comment by ddgenome** [comment]
The `copyfiles` node package does nothing and exits with zero status if there are no files matching the source glob pattern. So copying `src/**/*.graphql` to the `build` directory using that should be fine.

**Comment by ddgenome** [comment]
There does not seem to be a way get gql-gen to do a no-op if there are no files matching the glob pattern. So I think we will have to wrap the `gql-gen` command or write our own command that uses the same code generation logic but exits with a zero status of the provided glob pattern does not match any files. We can incorporate this into the unified CLI, like the old git-info command.

Useful links:

-   https://github.com/isaacs/node-glob
-   https://github.com/dotansimha/graphql-code-generator
-   https://www.npmjs.com/package/ok-file - would be nice to use but difficult to incorporate into a package script in a platform-independent way that exits successfully if there are no `*.graphql` files _and_ unsuccessfully if code generation fails

**Comment by ddgenome** [comment]
Let's see what this turns up: dotansimha/graphql-code-generator#167
