### ISSUE TITLE
mock GitHub so that no token is needed to run tests

### ISSUE THREAD

**Issue by claymccoy** [atomist/automation-client-ts#137]
## The Plan
I've been looking through the codebase trying to figure out how to remove the need to use GitHub tokens in our tests. At first, I thought that I would mock GitProject, but I don't think I need to. It looks like I could make a local git repo in a tmp dir and GitCommandGitProject would happily accept it. It is only the Github parts that I would need to mock, and that is all done with axios. I can avoid most of the GitHub calls by using local repos as the GitProject. In tests I'll use GitCommandGitProject.fromBaseDir(...) rather than GitCommandGitProject.cloned(...).

## The Problem With generatorEndToEndTest.ts  
The biggest offender is generatorEndToEndTest.ts which by it's name is an end to end test. Removing Github from this one is harder and arguably goes against the spirit of the test. If I did remove the GitHub and token usage from generatorEndToEndTest.ts, I could do it by providing an alternative to GitHubProjectPersister.ts and by removing its usage of gitHub.ts. It looks like gitHub.ts provides some optimized methods to get files directly without loading the whole repo. If the nature of the tests changed to be local, then these calls would no longer be needed as an optimization. Since there are no other usages of these token requiring, file accessing methods in gitHub.ts, they can be removed completely. (I'm purposely being a bit aggressive with that statement to see if I get any pushback.)

## Less Coverage Afterward
With those changes, we will no longer have token usage in our test code, and the operations will be local. The downside is that we will no longer have test coverage on some GitHub related code paths. GitHubProjectPersister.ts will no longer be executed in tests as it is now. Perhaps it can get its own dedicated tests that do some creative mocking. There are GitHub related parts of GitCommandGitProject.ts that will not be executed in tests. Some are conditional if a LocalRepoRef is provided.
I'd argue that the GitHub parts of GitCommandGitProject (like raisePullRequest() and createRepo()) should be somewhere else and tested very carefully. Then GitCommandGitProject really is focused on operating on a git project wherever it may be.

**Comment by claymccoy** [comment]
I wonder if I can integrate #121 into these changes.

**Comment by ddgenome** [comment]
Sounds good to me. I'd like to remove as much "surface area" in automation-client as we can, it's less to maintain and fewer restrictions moving forward.

Do you think it would be worthwhile to move some portion of these tests to the `test-api` directory, using that as a small set of integration tests that do require a GitHub token? This would be in addition to your proposed changes and would hopefully address the "Less Coverage Afterward" concern you raised, to the extent "some portion" restores coverage.

**Comment by johnsonr** [comment]
Looks like a sound a plan. Note that we can also mock GitHub by passing a `ProjectPersister` to the `generate` function that uses git locally and then does something with a random delay. For the immediate need between now and next week that might be the first thing to do.

**Comment by claymccoy** [comment]
Okay great. In the short term we can move the existing end to end test into "test-api". I can replace it with something that mocks ProjectPersister and opens the door to load testing.
I could follow the same formula as "test-api" and have a "test-load" which can be run separately from everything else and has some configuration for how hard it hits something like a generatorEndToEndTest with a ProjectPersister that has some fake latency (sleep). I'll probably start here, and then move on to properly mocking the rest.

**Comment by ddgenome** [comment]
This is done enough, right?
