### ISSUE TITLE
buttonForCommand parameters argument should be typed

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client-ts#151]
Used a TypeScript index signature:

```interface SquareConfig {
    color?: string;
    width?: number;
    [propName: string]: string | number;
}
```

See https://www.typescriptlang.org/docs/handbook/interfaces.html

**Comment by johnsonr** [comment]
See `Fix` in `ReviewResult`. Potentially that type could be moved for this and `fix` field of `ReviewComment` could be of the new type.

**Comment by cdupuis** [comment]
Makes sense.

**Comment by cdupuis** [comment]
Implemented in master now.
