### ISSUE TITLE
in `atomist config` please make it tell me what my configuration is

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client-ts#251]

**Comment by ddgenome** [comment]
Could you provide more detail here? You want it to dump the contents of ~/.atomist/client.config.ts to the terminal? Do you want this in all cases or do you want it to have different behavior depending on whether the file exists or, in its opinion, is complete?

**Comment by jessitron** [comment]
Good question. I meant, in the case where it tells me my config is ok, I would like it to tell me what team I’m connecting to, and other info if it has it. So if I don’t know what Atomist config does, I can learn by typing it.

**Comment by ddgenome** [comment]
Released
