### ISSUE TITLE
When a token is missing, give an error message that tells how to set it

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client-ts#253]
like, we deployed a client to cloud foundry, and it didn't have the environment variables to find its token. The error message indicated : "UnhandledPromiseRejectionWarning: Error: configuration is missing requires properties: token"
Please have it say how to provide the token. (GITHUB_TOKEN env var works)

**Comment by ddgenome** [comment]
In general, the configuration is supplied as JSON and it is telling you what key of the JSON is missing. You can fix it by adding the required key with a value. For some required keys, it is possible to specify them as environment variables, for others, not. How would you recommend the wording be changed to account for these possibilities?

**Comment by jessitron** [comment]
We could link to docs? or else specify an action or two they could take. `Supply a token property in a the configuration object in atomist.config.js, or else define GITHUB_TOKEN environment variable`

**Comment by ddgenome** [comment]
Was the change I made not sufficient? https://github.com/atomist/automation-client-ts/commit/ff4b66c87dfd13bc2e3282cf45e9c631b3e403c1

> you must set a 'token' property in your configuration or the ATOMIST_TOKEN environment variable

**Comment by jessitron** [comment]
oh shoot, I answered your question without noticing the commit. Sorry about that.

yes, the change is good 👍 

is GITHUB_TOKEN supported for legacy reasons?

**Comment by ddgenome** [comment]
> is GITHUB_TOKEN supported for legacy reasons?

Yes
