### ISSUE TITLE
Throw an error when .respond() is called from an event handler

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client-ts#3]
... or any time there's no address information in an event handler.

**Comment by cdupuis** [comment]
That's already implemented. Isn't that working?

**Comment by cdupuis** [comment]
See https://github.com/atomist/automation-client-ts/blob/master/src/internal/transport/websocket/WebSocketMessageClient.ts#L90

**Comment by jessitron** [comment]
nope, I spent a couple hours trying to get a message-update to work, and it turned out to be, no address info, because it was an event handler and I called .respond

**Comment by jessitron** [comment]
0.1.3
