### ISSUE TITLE
Update to more-standard node project format

### ISSUE THREAD

**Issue by jessitron** [atomist/automation-client-ts#328]
We talked about changing our build to be more standard and compatible with node tooling.
• put index.js (and therefore index.ts) at the top level of the project
• put build output in with the source files, so that we can reference them from the top level
• why: `npm publish` will just work with no custom steps; `npm link` will work; IntelliJ and VSCode will import from the correct place (top level) by default
• all imports will be from top level; anything deeper is a code review violation
• put source and output in lib/ rather than src/ (we are moving toward node conventions, away from JVM conventions)
• leave the tests in a separate tree.

**Comment by jessitron** [comment]
Here is a plan:
[ ] find everything imported from here by all projects in atomist and atomisthq orgs
[ ] export all of those from index.ts here
[ ] update all downstream projects to import everything from top level
[ ] rearrange this project as desired

**Comment by jessitron** [comment]
after this is done for all projects we can change atomist-sdm to use a straight `npm publish`

**Comment by ddgenome** [comment]
I'm working on atomist/cli and atomist/automation-seed-ts.
