### ISSUE TITLE
Use public email address when committing

### ISSUE THREAD

**Issue by ddgenome** [atomist/automation-client-ts#332]
Always use an email address registered with GitHub.com when committing and pushing.

https://atomist-community.slack.com/archives/C29DMA0R4/p1533302548000362

**Comment by weisheme** [comment]
Perhaps not directly related, but last week a related change was made https://github.com/atomist/automation-client-ts/issues/322

**Comment by ddgenome** [comment]
OK, maybe this was already fixed and node-automation just needs its dependencies updated.

**Comment by ddgenome** [comment]
Indeed: https://github.com/atomist/automation-client-ts/commit/305114f6ace783cb52f857abde3ec1801521fa5d

I'll close this and just update and release node-automation.
