### ISSUE TITLE
Feedback on graphClient.executeQueryFromFile versus graphClient.query

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/automation-client-ts#334]
```
ctx.graphClient.executeQueryFromFile<PodDeployments.PodDeployment, PodDeployments.Variables>(
        "./src/graphql/query/podDeployments.graphql",
        {
        });
```
versus

```
ctx.graphClient.query<PodDeployments.PodDeployment, PodDeployments.Variables>(
       {name: "podDeployments",
        options: {}}
        );
```

I think the latter is preferred, where you use the convention for how graphql query files are laid out in the underlying node module.  

There is still a potential difference between the name of the graphql file and and the name of the graphql query in that file.  For some reason, I was sort of expecting those graphql files to have been indexed by the  names of the queries they contain so it was only on my second run through that I tried using the query's filename.  

I also had an issue where I had a mutation graphql in the query directory and then had some difficult figuring out that I needed to use the `mutation` api, and move the file into the other structure.  The convention seems good but I think there are some important missing docs here.  The GraphClient interface mentions " Run query either provided as a string or as loaded from a file" but the QueryOptions doesn't have enough context to figure out this convention. 

The exmaples here:  https://docs.atomist.com/developer/graphql/ do not refer to the `query` api so also wnat to confirm that we should be using this one.

**Comment by cdupuis** [comment]
Yeah, this is all about outdated docs here. No actual code error here. 

You can do use the relative path with the query api.

**Comment by kipz** [comment]
Yeah, I wasted a bunch of time on this too.

1. executeQueryFromFile talks about relative paths to the root. I couldn't get this to work in the end. I wasn't sure where in the root the file ends up after building, and after a few tries, I followed the `query` approach mentioned above.
2. I was expecting this to take the name of the query, not the name of the file. IMO, we should either enforce that both are the same, or use the query name as the first argument.

**Comment by cdupuis** [comment]
re 1 the executeFrom API is deprecated and will get removed soon. 

re 2 that would be an easy change but likely backwards breaking. Looking into it.

**Comment by cdupuis** [comment]
Making the `{ name: }` of the options passed to `subscription, query and mutate` the name of the subscription, query and mutation inside the graphql file, seems better to me too. But I do worry about this being a backwards breaking change. 

What do you think about this @ddgenome?

**Comment by ddgenome** [comment]
That change is fine with me but I do think we'd need to support name as either for a bit.

**Comment by cdupuis** [comment]
Sounds good. I'll make that change and emit a warning if the file name doesn't match the name of the operation inside the file.
