### ISSUE TITLE
client.config.json stored in incorrect directory on Windows

### ISSUE THREAD

**Issue by jwalter** [atomist/automation-client-ts#44]
configuration.ts writes and reads client.config.json using process.env.HOME. This environment variable is not standard on Windows (at least modern versions), leading to the file being stored in a folder called 'undefined' in the directory where the command was executed. For Windows, process.env.USERPROFILE is what's normally used.

**Comment by ddgenome** [comment]
Thanks for this issue and thanks for the PR #45 .

If any other issues come up please let us know.

**Comment by ddgenome** [comment]
Thanks again for the issue and the fix, before I close this would you be willing to answer this question: are the forward slash `/` and leading `.` acceptable on MS Windows?

**Comment by jwalter** [comment]
Generally, yes. I can't recall ever having an issue with node based stuff on Windows that was caused by using slash or leading dot.

**Comment by ddgenome** [comment]
This is all merged and built. It will go out in the next release.

**Comment by johnsonr** [comment]
I'm going to do a `0.2.2` release shortly, which will include this.

**Comment by ddgenome** [comment]
The sof-command repo has been updated to 0.2.2, closing.
