### ISSUE TITLE
Ensure no contention with concurrent checkouts of the same directory

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client-ts#48]
Affects `StableDirectoryManager`.

Possible solutions:

- Locking mechanism with backoff
- Using an independent short-lived directory if the persistent one is already in use

**Comment by jessitron** [comment]
this will be solved with #58

**Comment by cdupuis** [comment]
@jessitron what is the state of this? can this be closed?

**Comment by jessitron** [comment]
this is implemented in ConcurrentDirectoryManager, which is still not the default. (with Using an independent short-lived directory if the persistent one is already in use)

We can close this one
