### ISSUE TITLE
Create unified atomist CLI that has subcommands

### ISSUE THREAD

**Issue by ddgenome** [atomist/automation-client-ts#55]
Rather than have multiple scripts that each do one thing, create a unified script that can start the client, login/config, do whatever the CLI does, etc.

**Comment by johnsonr** [comment]
Could we have an interim stage of documenting the present CLI and explaining how people can use that?

**Comment by ddgenome** [comment]
Here's a start: #95 

Still more to do.

**Comment by ddgenome** [comment]
Complete with release of 0.3.4
