### ISSUE TITLE
The repository cache should be under ~/.atomist

### ISSUE THREAD

**Issue by ddgenome** [atomist/automation-client-ts#63]
Currently, the cache of checked out repos is `~/.atomist-working`, it should be under the `~/.atomist/` directory we already use rather than creating another top-level directory in people's home directory. We should also add a directory for provider to avoid conflicts of same-named repos in different providers. I propose `~/.atomist/repos/PROVIDER/OWNER/REPO`.

**Comment by johnsonr** [comment]
I'm happy for this change to be made

**Comment by ddgenome** [comment]
We probably should consider using a standard layout: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by ddgenome** [comment]
@jessitron did any of your caching work change the location of the cache?
