### ISSUE TITLE
Add support for parsing and editing JavaScript/TypeScript AST

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client-ts#77]
_Moved from https://github.com/atomist/antlr-ts/issues/4. As TypeScript is core to Atomist, there should be a modest amount of code required, and as we already have a dependency on the TypeScript parser, this support should live here._

Please see the new `ts-parse` branch. This shows the start of adding TypeScript (and JS) support to our `TreeNode` and path expression model. The support should parallel the `MicrogrammarBasedFileParser`, which is why I've copied some of the tests over.

To make this work, we need to get a better grasp on what the TypeScript AST looks like. In particular:

- Extract node names robustly
- Correctly extract positions from TypeScriptElements

**Comment by johnsonr** [comment]
Needs plenty more testing and hardening, but this seems to basically working now, for parsing (probably not update). Would also be good to try with JavaScript.

**Comment by johnsonr** [comment]
Should automatically use the correct parser target (such as `JS` or `TSX`) for the file extension.

**Comment by kristianmandrup** [comment]
Great! I will dive in next week and see if I can help make this happen. Have a few things to wrap up before flying to Thailand on Sunday ;)

**Comment by johnsonr** [comment]
I put in a PR to get this into `master` as I don't see any reason not to. We can work on additional enhancements and stronger testing in new issues/PRs.
